import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import Rightbar from '../comps/rightBar';
import { Grid } from '@mui/material';
import Card from '@/comps/card';
<<<<<<< HEAD
=======
import "bootstrap/dist/css/bootstrap.min.css"

>>>>>>> cards


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>todo list</title>
      </Head>
      <main className={styles.main}>
        <Grid container>
          <Grid sm={3}>
            <Rightbar />
          </Grid>
          <Grid sm={9}>
            <Card />
          </Grid>
        </Grid>
      </main>
    </>
  )
}
